#!/usr/bin/env bash
# ARP Platform — local installer (venv, deps, .env, data dirs)
# Invoked by ./SETUP — do not run directly unless you know what you are doing.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PYTHON="${PYTHON:-python3}"
MIN_PY_MAJOR=3
MIN_PY_MINOR=11

step() { echo; echo "==> $*"; }
ok()   { echo "    OK: $*"; }
warn() { echo "    NOTE: $*" >&2; }
fail() { echo "    ERROR: $*" >&2; exit 1; }

py_ok() {
  "$PYTHON" -c "import sys; raise SystemExit(0 if sys.version_info >= (${MIN_PY_MAJOR}, ${MIN_PY_MINOR}) else 1)" 2>/dev/null
}

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║       ARP Global Capital — Local Platform Installer          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo "    Project folder: $ROOT_DIR"
echo

step "Checking Python ${MIN_PY_MAJOR}.${MIN_PY_MINOR}+"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  fail "Python not found. Install Python 3.11+ from https://www.python.org/downloads/ then re-run ./SETUP."
fi
if ! py_ok; then
  ver=$("$PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "unknown")
  fail "Found Python $ver but need ${MIN_PY_MAJOR}.${MIN_PY_MINOR}+."
fi
ok "$("$PYTHON" --version 2>&1)"

step "Python virtual environment (.venv)"
if [[ -d "$ROOT_DIR/.venv" ]]; then
  ok "Using existing .venv"
else
  "$PYTHON" -m venv "$ROOT_DIR/.venv"
  ok "Created .venv"
fi
# shellcheck disable=SC1091
source "$ROOT_DIR/.venv/bin/activate"
PYTHON="$ROOT_DIR/.venv/bin/python"

step "Installing Python packages (requirements.txt)"
if [[ "${ARP_INSTALL_FORCE:-0}" == "1" ]] \
   || ! "$PYTHON" -c "import fastapi, streamlit, uvicorn, yfinance" 2>/dev/null; then
  "$PYTHON" -m pip install --upgrade pip -q
  "$PYTHON" -m pip install -r "$ROOT_DIR/requirements.txt" -q
  ok "Dependencies installed"
else
  ok "Dependencies already present (set ARP_INSTALL_FORCE=1 to reinstall)"
fi

step "Preparing data folders"
mkdir -p "$ROOT_DIR/data" "$ROOT_DIR/data/chroma"
ok "data/ and data/chroma/ ready"

step "Environment file (.env)"
ENV_FILE="$ROOT_DIR/.env"
if [[ -f "$ENV_FILE" ]]; then
  ok "Keeping existing .env (not overwritten)"
  _env_patched=0
  if grep -qE '^DB_PATH=/data/' "$ENV_FILE" 2>/dev/null; then
    sed -i.bak 's|^DB_PATH=/data/|DB_PATH=./data/|' "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    _env_patched=1
  fi
  if grep -qE '^CHROMA_PATH=/data/' "$ENV_FILE" 2>/dev/null; then
    sed -i.bak 's|^CHROMA_PATH=/data/|CHROMA_PATH=./data/|' "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    _env_patched=1
  fi
  if grep -qE '^OLLAMA_HOST=http://ollama:' "$ENV_FILE" 2>/dev/null; then
    sed -i.bak 's|^OLLAMA_HOST=http://ollama:|OLLAMA_HOST=http://localhost:|' "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    _env_patched=1
  fi
  if grep -qE '^API_URL=http://backend:' "$ENV_FILE" 2>/dev/null; then
    sed -i.bak 's|^API_URL=http://backend:|API_URL=http://localhost:|' "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    _env_patched=1
  fi
  if [[ "$_env_patched" -eq 1 ]]; then
    ok "Patched Docker-style paths in .env → local (./data/, localhost)"
  fi
else
  if [[ -t 0 ]]; then
    echo
    echo "    Choose a default market data source for local runs:"
    echo "      1) mock          offline modelled prices (recommended)"
    echo "      2) yahoo         Yahoo Finance (live)"
    echo "      3) alphavantage  Alpha Vantage (needs API key in .env later)"
    read -r -p "    Choice [1-3, default 1]: " _md_choice
    case "${_md_choice:-1}" in
      2) _MARKET_DATA_SOURCE="yahoo" ;;
      3) _MARKET_DATA_SOURCE="alphavantage" ;;
      *) _MARKET_DATA_SOURCE="mock" ;;
    esac
  else
    _MARKET_DATA_SOURCE="mock"
  fi

  cat >"$ENV_FILE" <<EOF
# ARP Platform — local environment (generated by SETUP)
# Edit as needed; never commit this file.

DB_PATH=./data/arp.db
OLLAMA_HOST=http://localhost:11434
OLLAMA_MODEL=phi3:mini
API_URL=http://localhost:8000
ENABLE_ENHANCEMENTS=1

MARKET_DATA_SOURCE=${_MARKET_DATA_SOURCE}
ALPHA_VANTAGE_API_KEY=
AV_BASE_URL=https://www.alphavantage.co/query
ALPHA_VANTAGE_ENTITLEMENT=delayed
AV_REQUEST_SLEEP=0.9

ENABLE_RAG=1
VECTOR_DB=local
CHROMA_PATH=./data/chroma
OLLAMA_EMBED_MODEL=nomic-embed-text
RAG_TOP_K=3

MEMORY_ENABLED=1
MEMORY_RECALL_LIMIT=3
MEMORY_MAX_PER_USER=200

ARP_RELOAD=0
EOF
  ok "Created .env (market data: ${_MARKET_DATA_SOURCE})"
fi

step "Checking Ollama (local LLM — optional)"
_ollama_ok=0
if command -v ollama >/dev/null 2>&1; then
  _ollama_ok=1
  ok "ollama CLI found"
elif command -v curl >/dev/null 2>&1 && curl -sf "http://localhost:11434/api/version" >/dev/null 2>&1; then
  _ollama_ok=1
  ok "Ollama API responding on localhost:11434"
else
  warn "Ollama not detected. Platform runs without it; AI agents use a graceful fallback."
  warn "Install from https://ollama.com/ then run: ollama pull phi3:mini"
fi

if [[ "$_ollama_ok" -eq 1 && -t 0 ]]; then
  echo
  read -r -p "    Pull recommended models now? (phi3:mini + nomic-embed-text) [y/N]: " _pull
  _pull_ans=$(printf '%s' "$_pull" | tr '[:upper:]' '[:lower:]')
  if [[ "$_pull_ans" == "y" || "$_pull_ans" == "yes" ]]; then
    if command -v ollama >/dev/null 2>&1; then
      echo "    Pulling phi3:mini (may take a few minutes)…"
      ollama pull phi3:mini || warn "phi3:mini pull failed — retry later with: ollama pull phi3:mini"
      echo "    Pulling nomic-embed-text (RAG embeddings)…"
      ollama pull nomic-embed-text || warn "nomic-embed-text pull failed — RAG uses offline fallback until pulled"
    else
      warn "ollama CLI not in PATH; skip model pull or install Ollama app."
    fi
  fi
fi

step "Quick import check"
"$PYTHON" -c "import fastapi, streamlit, uvicorn; print('    OK: core packages import cleanly')"

echo
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    Installation complete                     ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo
echo "  Next step — launch the platform:"
echo
echo "    • Double-click  EXEC   (macOS Finder)"
echo "    • Or run:       ./EXEC   (./SETUP was the installer you just ran)"
echo
echo "  Then open:  http://localhost:8501"
echo "  Login:      paste a bearer token printed when EXEC seeds the database"
echo
if [[ "$_ollama_ok" -eq 0 ]]; then
  echo "  Optional: install Ollama for live AI agent replies"
  echo "            https://ollama.com/"
  echo
fi
